---
- name: configure apache2 using child playbooks
  hosts: all
  tasks:
    - name: call playbooks for installation
      include_tasks: "{{item}}"
      with_items:
        - install.yml
        - edit_index.yml
        - restart.yml
        - check_url_response.yml
...
