---
- name: Implementing tags
  hosts: all
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present
        update_cache: no
      tags:
       - install
       - nginx_install
       - always
    - name: install tomcat10
      apt:
        name: tomcat10    
        state: present
        update_cache: no
      tags:
        - install
        - install_tomcat10
    - name: restart nginx
      service:
         name: nginx
         state: restarted
      tags:
        - restart
        - nginx_restart
        - never  
    - name: Restart tomcat10
      service:
         name: tomcat10
         state: restarted
      tags:
        - restart
        - tomcat10_restart     

