---
- name: check if f1 dir is present if not create a file f1
  hosts: all
  tasks:
    - name: check for f1 dir
      stat:
        path: /home/ubuntu/f1
      register: a
    - name: Display output of above module
      debug:
        var: a
    - name: create f1 file if f1 folder or directory is not present
      file:
        name: /home/ubuntu/f1
        state: touch
      when:
        a.stat.exists == false
