---
- name: Configure tomcat using loops
  hosts: all
  tasks:
    - name: Install tomcat10 and tomcat10-admin
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tomcat10,b: present,c: yes}
        - {a: tomcat10-admin,b: present,c: no}
    - name: Copy customsied tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
    - name: Change port of tomcat from 8080 to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat10/server.xml
    - name: Restart tomcat1
      service:
        name: tomcat10
        state: restarted
    - name: Pause for 40 seconds
      pause:
        seconds: 40
    - name: Check tomcat on all the servers
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.27.52:9090
        - http://172.31.25.142:9090
...
