---
- name: using loop in ansible
  hosts: all
  tasks:
    - name: install softwares
      apt:
        name: "{{item}}"
        state: present
        update_cache: no
      with_items: 
         - tree
         - maven
         - git
