---
- name: install git on ubuntu servers
  hosts: ubuntu
  tasks:
    - name: install git using apt
      apt:
        name: git
        state: present
        update_cache: no
- name: install git on redhat server
  hosts: redhat
  tasks:
    - name: install git
      yum: 
        name: git
        state: present
        update_cache: no

