---
- name: configure jenkins and required s/w's
  hosts: jenkinsserver
  tasks:
    - name: install requred softwares
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
         - {a: openjdk-17-jdk,b: present,c: yes}
         - {a: git,b: present,c: yes}
         - {a: maven,b: present,c: yes}
    - name: Download jenkins.war
      get_url:
        url: https://get.jenkins.io/war-stable/2.541.1/jenkins.war
        dest: /home/ubuntu
- name: configure tomcat qa and prod servers
  hosts: servers
  tasks:
    - name: install tomcat on qa and prod server
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tomcat10,b: present,c: no}
        - {a: tomcat10-admin,b: present,c: no}
    - name: change port of tomcat
      replace:
        regexp: 8080
        replace: 9092
        path: /etc/tomcat10/server.xml
    - name: edit tomcat users.xml
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10
      notify: Restart tomcat
  handlers:
    - name: Restart tomcat
      service:
         name: tomcat10
         state: restarted    
