---
- name: implementing loops
  hosts: all
  tasks:
    - name: install or uninstall or upgrade softwares
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      loop:
        - {a: tree,b: present,c: no}
        - {a: git,b: absent,c: no}
        - {a: maven,b: latest,c: no}
...   
