$ANSIBLE_VAULT;1.1;AES256
36613261363466653632643333323333346332663133613530323263646232376530316564303261
6532373836393366393735633037363733663234393836660a393636623739326566396539366235
39323039646533313131616438386362396566333134326139313138366231653930333634616562
3939316237643732340a646365643132646530396166656464386361626662333037653836343937
66353333313930313930396638343663613835336364303064396261383637643461633362633066
34343137363632306534653162666133623465306262623063376363353537363261333738323237
63616131386466303834386232383433303330333538633533623233643865306431353062323164
35303763383061323035303432313166356666373830386163643965646236626261343232376239
38323261393066353361373631353964333039316631666131656639353766383962623933366338
39643531656635613965636431646636396361363831356639303933376565333535656164326138
34373561356232366235366133353565336261373832616366366230326133613964353566346431
39626237633033393562393166653562643437666165353761373765373464373838316131623734
31383838623738343033643938323736323738643437346466653937356636313062313839323337
33333335396163653765646665373533633539303563656463383535303835666363303261396436
61373037353566363266643834316334373239393466366664326632666163333037313732343531
62636565623162616130356161363062333932303537623934313739313664313339623765336561
33393938386637393064363263316663323439386565646136373133653938646236
