---
- name: capture OS flavours using environmental variables
  hosts: all
  tasks:
    - name: Display OS name
      debug:
        var: "ansible_distribution"
    - name: display OS version
      debug:
        var: "ansible_distribution_version"
    - name: display OS major version
      debug:
        var: "ansible_distribution_major_version"

