$ANSIBLE_VAULT;1.1;AES256
30613639663234356635616436326164303932353065306665643035303132633435643264316563
6564346437303835383763363464636230336535393734370a343831376239613365333361616639
36623232613037363637316534333462396635373835383533373138613336633332373931656462
6238323830343235650a653262643665623164653062353839623535633730616163613536346633
64653165666133353266666434633239306536643735383565653239616466323064356535376661
37396463646161653638656266613366386234663639356531303234326366353964376261333961
63353361363933353631646363623038383839623035653233316263346366623365383462333330
33643764333861343233333961663137356335623565343031373562653237343263363532393165
30633530353362613831373934343938313637383564386532366239323431343364646130643934
64626638663935373966373435326666363766326132616166646265336365633435393565383665
38633539643237343466376362363930393065373232383631373430343035613866613863336532
62383235306465326432376563633265393565326262336633356236353364333065393532623531
3430
