---
- name: configure tomcat softwares
  hosts: all
  become: yes

  tasks:
    - name: install tomcat-10
      apt:
        name: tomcat10
        state: present
        update_cache: false

    - name: install tomcat10-admin
      apt:
        name: tomcat10-admin
        state: present

    - name: copy customised tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat10/tomcat-users.xml

    - name: change port of tomcat10 from 8080 to 9090
      replace:
        path: /etc/tomcat10/server.xml
        regexp: '8080'
        replace: '9090'

    - name: restart tomcat10
      service:
        name: tomcat10
        state: restarted
    - name: pause for some time 
      pause:
        seconds: 20

    - name: check tomcat
      uri:
        url: "http://172.31.27.52:9090"
        status_code: 200
    - name: check tomcat
      uri:
        url: "http://172.31.25.142:9090"
        status_code: 200


