---
- name: implementing tags
  hosts: all
  tasks:
    - name: install tree
      apt:
        name: tree
        state: present
        update_cache: no
      tags: tree_installation
    - name: create user
      user:
        name: Anu
        password: Anu@
      tags: user_creation
    - name: copy passwd file
      copy:
        src: /etc/passwd
        dest: /tmp
